### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by demist** [FlyLikeSoarin/ConCiv#1]
+ зачем нам нужен класс UnitBuilding, ведь, насколько это понятно из архитектуры, у нас есть прототипы? Т.е. зачем два разных сценария создания юнитов?

**Comment by FlyLikeSoarin** [comment]
На сколько я понял прототип не занимается созданием юнитов, он должен заниматься только клонированием уже готовых, для дальнейшего использования в программе. Поэтому для их инициализации создан UnitBuilder. То есть UnitBuilder инициализирует объекты юнитов, а прототип их клонирует.

Конечно можно было сделать метод, который создаёт юнит у класса UnitPrototype, но мне показалось это менее логичным, ведь список юнитов может расширятся во время игры, и хотелось бы давать прототипу на вход уже инициалированные юниты. Города же в свою очередь всегда появляются одинаковыми поэтому они берутся сразу из Строителя.

**Comment by demist** [comment]
понял, принято.

**Comment by demist** [comment]
засчитано
